# Generated by Django 5.1.1 on 2024-09-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="appuser",
            name="profile_url",
            field=models.URLField(blank=True),
        ),
    ]
