# Generated by Django 5.1.1 on 2024-09-30 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0003_product_repository_release_productrepository_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="releases.appuser",
            ),
        ),
        migrations.AddField(
            model_name="productrepository",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="releases.appuser",
            ),
        ),
        migrations.AddField(
            model_name="release",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="releases.appuser",
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="releases.appuser",
            ),
        ),
        migrations.AddField(
            model_name="semanticrelease",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="releases.appuser",
            ),
        ),
    ]
