# Generated by Django 5.1.1 on 2024-09-30 16:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0004_product_user_productrepository_user_release_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semanticrelease",
            name="product",
        ),
    ]
