# Generated by Django 5.1.1 on 2024-09-30 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0005_remove_semanticrelease_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semanticrelease",
            name="releases",
        ),
        migrations.AddField(
            model_name="semanticrelease",
            name="release",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="releases.release",
            ),
        ),
    ]
