# Generated by Django 5.1.1 on 2024-10-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0006_remove_semanticrelease_releases_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="semanticrelease",
            name="footer_image_url",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="semanticrelease",
            name="header_image_url",
            field=models.URLField(null=True, unique=True),
        ),
    ]
