# Generated by Django 5.1.1 on 2024-10-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0007_semanticrelease_footer_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semanticrelease",
            name="footer_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="semanticrelease",
            name="header_image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="semanticrelease",
            name="release_body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
