# Generated by Django 5.1.1 on 2024-10-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0008_alter_semanticrelease_footer_image_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="semanticrelease",
            name="release_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
