# Generated by Django 5.1.1 on 2024-10-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0009_semanticrelease_release_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="release",
            name="release_url",
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name="release",
            unique_together={("user", "release_url")},
        ),
        migrations.AddField(
            model_name="repository",
            name="forks_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="full_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="stargazers_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="watchers_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
