# Generated by Django 5.1.1 on 2024-10-04 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0010_repository_forks_count_repository_full_response_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="watchers_count",
        ),
    ]
