# Generated by Django 5.1.1 on 2024-10-09 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0011_remove_repository_watchers_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="forks_count",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="full_response",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="stargazers_count",
        ),
    ]
