# Generated by Django 5.1.3 on 2025-02-04 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0013_alter_appuser_user"),
        ("user_org", "0002_alter_project_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="active_org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_org.organization",
            ),
        ),
    ]
