# Generated by Django 5.1.6 on 2025-03-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0014_appuser_active_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="company_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("marketing", "Marketing"),
                    ("developer_relations", "Developer Relations"),
                    ("sales", "Sales"),
                    ("content_creator", "Content Creator"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="usage_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("creating_videos", "Creating new videos"),
                    ("editing_videos", "Editing videos"),
                    ("screen_capture", "Screen capture"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
