# Generated by Django 5.1.6 on 2025-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0015_appuser_company_role_appuser_usage_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
