# Generated by Django 5.1.6 on 2025-03-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0016_appuser_verification_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="subscription_renewal_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
