# Generated by Django 5.1.6 on 2025-03-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0017_appuser_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="has_subscription_access",
            field=models.BooleanField(default=False),
        ),
    ]
