# Generated by Django 5.2.4 on 2025-08-06 18:39

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Name of the Celery task", max_length=255
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        help_text="Celery task ID", max_length=255, unique=True
                    ),
                ),
                ("args", models.JSONField(default=list, help_text="Task arguments")),
                (
                    "kwargs",
                    models.JSONField(default=dict, help_text="Task keyword arguments"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the task",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "task_api_execution",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="task_api_ex_user_id_8fc581_idx",
                    ),
                    models.Index(
                        fields=["celery_task_id"], name="task_api_ex_celery__7b302d_idx"
                    ),
                ],
            },
        ),
    ]
