# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_stages: [pre-commit, manual]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
        types_or: [python, pyi]
        require_serial: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml # Checks yaml files for parseable syntax.
      - id: check-json # Checks json files for parseable syntax.
      - id: check-added-large-files
        exclude: '^uv.lock$'
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
        exclude: "^kedro/templates/|^features/steps/test_starter/"
      - id: requirements-txt-fixer # Sorts entries in requirements.txt

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0 # Use the latest stable version
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: >-
          (?x)^(
            .*\.(jpeg|jpg|png|gif|eot|woff|woff2|ttf|svg|ico)|
            \.gitignore|
          )$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, markdown]

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c "cd web && yarn lint --fix"
        language: system
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false
        always_run: true
        files: ^web/

  - repo: local
    hooks:
      - id: django-test
        name: django-test
        # entry: uv run python app/manage.py test
        entry: bash -c "git diff --name-only HEAD | grep -q '\.py$' && uv run app/manage.py test || echo 'No .py file changes detected, skipping tests.'"
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
