# fly.toml app configuration file for gestral
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gestral'
primary_region = 'yyz'
console_command = 'python manage.py shell'

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = 'python manage.py migrate --verbosity=2'

[env]
  PORT = '8000'
  DJANGO_SETTINGS_MODULE = 'settings'
  DEBUG = false
  ENVIRONMENT = 'production'
  ALLOWED_HOSTS = '*.fly.dev,gestral.fly.dev'
  CORS_ALLOWED_ORIGINS = 'https://gestral.fly.dev'
  CSRF_TRUSTED_ORIGINS = 'https://gestral.fly.dev'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = 'gunicorn --bind :8000 --workers 2 wsgi:application'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/static'
  url_prefix = '/static/'
