# Generated by Django 5.1.3 on 2025-02-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="capture",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
