# Generated by Django 5.1.5 on 2025-02-21 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0003_brandasset"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BrandAsset",
        ),
    ]
