# Generated by Django 5.1.3 on 2025-02-24 01:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0004_delete_brandasset"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("colors", models.JSONField(default=list)),
                ("logo", models.JSONField(default=dict)),
                ("font", models.JSONField(default=dict)),
                ("voiceover", models.JSONField(default=dict)),
                ("cover", models.JSONField(default=dict)),
                ("intro_video", models.JSONField(default=dict)),
                ("outro_video", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_assets",
                        to="user_org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Asset",
                "verbose_name_plural": "Brand Assets",
                "ordering": ["-created_at"],
            },
        ),
    ]
