# Generated by Django 5.1.5 on 2025-02-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0006_videoproject_videoasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (5, "5 seconds"),
                    (30, "30 seconds"),
                    (60, "60 seconds"),
                    (180, "3 minutes"),
                    (300, "5 minutes"),
                ],
                default=30,
            ),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="format",
            field=models.CharField(
                choices=[
                    ("16:9", "16:9 Landscape"),
                    ("9:16", "9:16 Portrait"),
                    ("1:1", "1:1 Square"),
                ],
                default="16:9",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="video_quality",
            field=models.CharField(
                choices=[("480p", "480p"), ("720p", "720p"), ("1080p", "1080p")],
                default="720p",
                max_length=10,
            ),
        ),
    ]
