# Generated by Django 5.1.5 on 2025-02-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0007_videoproject_duration_videoproject_format_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videoasset",
            old_name="video",
            new_name="video_project",
        ),
        migrations.AddField(
            model_name="videoasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generated", "Generated"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
