# Generated by Django 5.1.5 on 2025-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0008_rename_video_videoasset_video_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generated", "Generated"),
                    ("accepted", "Accepted"),
                    ("changes_requested", "Changes Requested"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
