# Generated by Django 5.1.5 on 2025-03-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0009_alter_videoasset_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoasset",
            name="rendered_video_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
