# Generated by Django 5.1.3 on 2025-03-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0010_videoasset_rendered_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoasset",
            name="render_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
