# Generated by Django 5.1.6 on 2025-03-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0011_videoasset_render_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoasset",
            name="audio_recordings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
