# Generated by Django 5.1.6 on 2025-03-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0012_videoasset_audio_recordings"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoasset",
            name="remotion_state",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
