# Generated by Django 5.1.6 on 2025-03-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0013_videoasset_remotion_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generated", "Generated"),
                    ("accepted", "Accepted"),
                    ("changes_requested", "Changes Requested"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
