# Generated by Django 5.1.6 on 2025-03-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0014_alter_videoasset_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoasset",
            name="video_recordings",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
