# Generated by Django 5.1.6 on 2025-03-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0015_videoasset_video_recordings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="capture",
            old_name="storage_dir",
            new_name="storage_url_path",
        ),
        migrations.RenameField(
            model_name="videoasset",
            old_name="remotion_state",
            new_name="state",
        ),
        migrations.RemoveField(
            model_name="videoproject",
            name="capture",
        ),
        migrations.AddField(
            model_name="videoproject",
            name="current_state",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="capture",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                    ("error", "Error"),
                    ("complete", "Complete"),
                    ("deleted", "Deleted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="capture",
            name="type",
            field=models.CharField(
                choices=[("video", "Video"), ("audio", "Audio"), ("screen", "Screen")],
                default="video",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processing", "Processing"),
                    ("complete", "Complete"),
                    ("error", "Error"),
                    ("deleted", "Deleted"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
