# Generated by Django 5.1.6 on 2025-03-13 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0017_rename_models_capture_and_videoasset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videoproject",
            old_name="current_state",
            new_name="state",
        ),
        migrations.RemoveField(
            model_name="rendervideo",
            name="audio_recordings",
        ),
        migrations.RemoveField(
            model_name="rendervideo",
            name="rendered_video_url",
        ),
        migrations.RemoveField(
            model_name="rendervideo",
            name="video_recordings",
        ),
        migrations.AlterField(
            model_name="rendervideo",
            name="video_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="render_videos",
                to="video_gen.videoproject",
            ),
        ),
        migrations.AlterField(
            model_name="rendervideo",
            name="video_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
