# Generated by Django 5.1.6 on 2025-03-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0018_rename_current_state_videoproject_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
