# Generated by Django 5.1.6 on 2025-03-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0019_videoproject_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("screen", "Screen"),
                    ("image", "Image"),
                ],
                default="video",
                max_length=20,
            ),
        ),
    ]
