# Generated by Django 5.1.6 on 2025-03-21 01:34

import django.db.models.deletion
from django.db import migrations, models


def assign_workspace_to_video_projects(apps, schema_editor):
    VideoProject = apps.get_model("video_gen", "VideoProject")
    Workspace = apps.get_model("user_org", "Workspace")

    for video_project in VideoProject.objects.all():
        # Find a workspace that belongs to the same organization as the video project
        workspace = Workspace.objects.filter(organization=video_project.org).first()
        if workspace:
            video_project.workspace = workspace
            video_project.save()


def cleanup_orphaned_projects(apps, schema_editor):
    """Delete any video projects that couldn't get a workspace assigned"""
    VideoProject = apps.get_model("video_gen", "VideoProject")
    # Delete any video projects with null workspace
    VideoProject.objects.filter(workspace__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("user_org", "0007_rename_project_workspace"),
        ("video_gen", "0020_alter_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_projects",
                to="user_org.workspace",
            ),
        ),
        migrations.RunPython(assign_workspace_to_video_projects),
        migrations.RunPython(cleanup_orphaned_projects),
        migrations.AlterField(
            model_name="videoproject",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_projects",
                to="user_org.workspace",
            ),
        ),
    ]
