# Generated by Django 5.1.6 on 2025-03-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0021_videoproject_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendervideo",
            name="render_speed",
            field=models.CharField(
                choices=[
                    ("fast", "Fast (Lower Quality)"),
                    ("medium", "Medium (Balanced)"),
                    ("slow", "Slow (High Quality)"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="rendervideo",
            name="resolution",
            field=models.CharField(
                choices=[
                    ("720p", "HD (720p)"),
                    ("1080p", "Full HD (1080p)"),
                    ("2160p", "Ultra HD (4K)"),
                ],
                default="720p",
                max_length=10,
            ),
        ),
    ]
