# Generated by Django 5.1.6 on 2025-03-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0022_rendervideo_render_speed_rendervideo_resolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="thumbnail_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
