# Generated by Django 5.1.6 on 2025-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0023_media_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
    ]
