# Generated by Django 5.1.6 on 2025-03-27 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0024_videoproject_is_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoproject",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="videoproject",
            name="video_quality",
        ),
    ]
