# Generated by Django 5.1.6 on 2025-03-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0025_remove_videoproject_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="tags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="rendervideo",
            name="tags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="tags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
