# Generated by Django 5.1.6 on 2025-04-01 04:10

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_org", "0008_anonymoussession"),
        ("video_gen", "0026_media_tags_rendervideo_tags_videoproject_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="caption_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="videoproject",
            name="anonymous_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_org.anonymoussession",
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_projects",
                to="user_org.workspace",
            ),
        ),
        migrations.CreateModel(
            name="VideoPipelineRun",
            fields=[
                (
                    "id",
                    common.fields.PrefixedUUIDField(
                        "vplr", primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "input_payload",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("input_config", models.JSONField(blank=True, default=dict, null=True)),
                ("logs", models.JSONField(blank=True, default=list, null=True)),
                ("error_logs", models.TextField(blank=True, null=True)),
                (
                    "video_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_pipeline_runs",
                        to="video_gen.videoproject",
                    ),
                ),
            ],
        ),
    ]
