# Generated by Django 5.1.6 on 2025-04-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0027_media_caption_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videopipelinerun",
            name="render_video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pipeline_runs",
                to="video_gen.rendervideo",
            ),
        ),
    ]
