# Generated by Django 5.1.6 on 2025-04-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0028_videopipelinerun_render_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoproject",
            name="preview_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="videopipelinerun",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
