# Generated by Django 5.1.6 on 2025-04-04 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0029_videoproject_preview_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="videoproject",
            old_name="format",
            new_name="aspect_ratio",
        ),
    ]
