# Generated by Django 5.1.6 on 2025-04-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0030_rename_format_videoproject_aspect_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendervideo",
            name="email_attempts",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="rendervideo",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
