# Generated by Django 5.1.6 on 2025-04-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0031_rendervideo_email_attempts_rendervideo_email_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendervideo",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
