# Generated by Django 5.1.6 on 2025-04-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0033_rendervideo_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rendervideo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generated", "Generated"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="videoproject",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processing", "Processing"),
                    ("generated", "Generated"),
                    ("accepted", "Accepted"),
                    ("changes_requested", "Changes Requested"),
                    ("complete", "Complete"),
                    ("error", "Error"),
                    ("deleted", "Deleted"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
