# Generated by Django 5.1.6 on 2025-05-10 13:59

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_org", "0009_anonymoussession_email"),
        ("video_gen", "0034_alter_rendervideo_status_alter_videoproject_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    common.fields.PrefixedUUIDField(
                        "rec", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="Recording Session", max_length=255)),
                ("daily_room_name", models.CharField(max_length=255, unique=True)),
                ("daily_room_url", models.URLField(max_length=500)),
                (
                    "daily_room_token",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("active", "Active"),
                            ("recording", "Recording"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                (
                    "s3_folder_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("recording_started_at", models.DateTimeField(blank=True, null=True)),
                ("recording_ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "daily_recording_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("daily_session_data", models.JSONField(blank=True, null=True)),
                ("tracks_downloaded", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="user_org.appuser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="user_org.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recording",
                "verbose_name_plural": "Recordings",
                "ordering": ["-created_at"],
            },
        ),
    ]
