# Generated by Django 5.1.6 on 2025-05-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0035_recording"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recording",
            name="daily_room_name",
            field=models.CharField(max_length=255),
        ),
    ]
