# Generated by Django 5.1.6 on 2025-05-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_org", "0009_anonymoussession_email"),
        ("video_gen", "0036_alter_recording_daily_room_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recording",
            name="daily_room_name",
        ),
        migrations.RemoveField(
            model_name="recording",
            name="daily_room_url",
        ),
        migrations.RemoveField(
            model_name="recording",
            name="org",
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("daily_room_name", models.CharField(max_length=255, unique=True)),
                ("daily_room_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_org.appuser",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_org.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("created_by", "org")},
            },
        ),
        migrations.AddField(
            model_name="recording",
            name="room",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordings",
                to="video_gen.room",
            ),
            preserve_default=False,
        ),
    ]
