# Generated by Django 5.1.6 on 2025-05-21 15:17

from django.db import migrations, models


def update_aspect_ratio_from_state(apps, schema_editor):
    RenderVideo = apps.get_model("video_gen", "RenderVideo")
    for render_video in RenderVideo.objects.all():
        if render_video.state and "aspectRatio" in render_video.state:
            # Map the state aspect ratio to the new field choices
            state_ratio = render_video.state["aspectRatio"]
            if state_ratio == "16:9":
                render_video.aspect_ratio = "16:9"
            elif state_ratio == "9:16":
                render_video.aspect_ratio = "9:16"
            elif state_ratio == "1:1":
                render_video.aspect_ratio = "1:1"
            else:
                # Default to 16:9 if the aspect ratio is not recognized
                render_video.aspect_ratio = "16:9"
            render_video.save()


def reverse_update_aspect_ratio(apps, schema_editor):
    # No need to reverse this data migration
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0038_add_render_video_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendervideo",
            name="aspect_ratio",
            field=models.CharField(
                choices=[
                    ("16:9", "16:9 Landscape"),
                    ("9:16", "9:16 Portrait"),
                    ("1:1", "1:1 Square"),
                ],
                default="16:9",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            update_aspect_ratio_from_state, reverse_update_aspect_ratio
        ),
    ]
