# Generated by Django 5.1.6 on 2025-05-23 20:24

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0039_rendervideo_aspect_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="duration_in_seconds",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mp4", "MP4"),
                    ("mov", "MOV"),
                    ("webm", "WEBM"),
                    ("m4v", "M4V"),
                    ("mpeg", "MPEG"),
                    ("mpeg4", "MPEG4"),
                    ("gif", "GIF"),
                    ("webp", "WEBP"),
                    ("png", "PNG"),
                    ("jpg", "JPG"),
                    ("jpeg", "JPEG"),
                    ("tiff", "TIFF"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="resolution",
            field=models.CharField(
                choices=[("sd", "SD"), ("hd", "HD"), ("uhd", "UHD")],
                default="hd",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="type",
            field=models.CharField(
                choices=[
                    ("studio_recording", "Studio Recording"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("screen", "Screen"),
                    ("image", "Image"),
                ],
                default="video",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rendervideo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("generated", "Generated"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="VideoProjectMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Order of media in the project"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_media",
                        to="video_gen.media",
                    ),
                ),
                (
                    "video_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_media",
                        to="video_gen.videoproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Project Media",
                "verbose_name_plural": "Video Project Media",
                "ordering": ["order", "-created_at"],
                "unique_together": {("video_project", "media")},
            },
        ),
    ]
