# Generated by Django 5.1.6 on 2025-07-14 20:58

from django.db import migrations
from pgvector.django import VectorField


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0041_migrate_media_video_project"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector CASCADE;",
        ),
        migrations.AddField(
            model_name="media",
            name="embedding",
            field=VectorField(
                blank=True,
                dimensions=1536,
                help_text="Vector embedding for semantic search (text-embedding-3-small)",
                null=True,
            ),
        ),
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector CASCADE;",
        ),
    ]
