# Generated by Django 5.1.6 on 2025-07-14 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0042_add_embedding_field"),
    ]

    operations = [
        # Ensure pgvector extension is enabled
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector CASCADE;",
        ),
        # Create HNSW index for efficient similarity search
        # HNSW (Hierarchical Navigable Small World) is optimized for similarity search
        # Note: Removed CONCURRENTLY as it cannot run in migration transactions
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS media_embedding_hnsw_idx ON video_gen_media USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64);",
            reverse_sql="DROP INDEX IF EXISTS media_embedding_hnsw_idx;",
        ),
        # Also create an IVFFlat index as an alternative
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS media_embedding_ivfflat_idx ON video_gen_media USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);",
            reverse_sql="DROP INDEX IF EXISTS media_embedding_ivfflat_idx;",
        ),
    ]
