# Generated by Django 5.1+ on 2025-07-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0043_add_pgvector_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="embedding_text",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="AI-generated multimodal summary of the media content",
            ),
        )
    ]
