# Generated by Django 5.1.6 on 2025-07-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video_gen", "0044_add_ai_summary_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="resolution",
            field=models.CharField(
                choices=[("720p", "Sd"), ("1080p", "Hd"), ("2160p", "Uhd")],
                default="1080p",
                max_length=20,
            ),
        ),
    ]
