# Generated by Django 5.2.6 on 2025-09-24 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_gen', '0001_squashed_0048_alter_media_embedding_alter_recording_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='video_gen.room'),
        ),
    ]
