# Generated by Django 5.1.6 on 2025-03-29 20:37

import common.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    common.fields.PrefixedUUIDField(
                        "license", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    common.fields.PrefixedUUIDField(
                        "mood", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("has_cover_art", models.BooleanField(default=False)),
                (
                    "cover_art_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    common.fields.PrefixedUUIDField(
                        "genre", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("has_cover_art", models.BooleanField(default=False)),
                (
                    "cover_art_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subgenres",
                        to="sound_gen.genre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    common.fields.PrefixedUUIDField(
                        "track", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("main_artists", models.JSONField(default=list)),
                ("featured_artists", models.JSONField(default=list)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="music/tracks/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["mp3", "wav"]
                            )
                        ],
                    ),
                ),
                ("preview_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "waveform_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("bpm", models.PositiveIntegerField(blank=True, null=True)),
                ("markers", models.JSONField(default=list)),
                ("length", models.PositiveIntegerField(help_text="Length in seconds")),
                ("images", models.JSONField(default=dict)),
                ("has_vocals", models.BooleanField(default=False)),
                ("is_explicit", models.BooleanField(default=False)),
                ("is_preview_only", models.BooleanField(default=False)),
                ("added", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "genres",
                    models.ManyToManyField(related_name="tracks", to="sound_gen.genre"),
                ),
                (
                    "license",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracks",
                        to="sound_gen.license",
                    ),
                ),
                (
                    "moods",
                    models.ManyToManyField(related_name="tracks", to="sound_gen.mood"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["id"], name="sound_gen_t_id_d1b572_idx"),
                    models.Index(
                        fields=["created_at"], name="sound_gen_t_created_b56844_idx"
                    ),
                ],
            },
        ),
    ]
