# Generated by Django 5.1.6 on 2025-03-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sound_gen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="audio_file",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="preview_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="waveform_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
