# Generated by Django 5.1.6 on 2025-03-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sound_gen", "0002_alter_track_audio_file_alter_track_preview_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="images",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
