# Generated by Django 5.1.6 on 2025-04-01 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0016_appuser_verification_sent_at"),
        ("sound_gen", "0003_alter_track_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="releases.appuser",
            ),
        ),
    ]
