# Generated by Django 5.1.1 on 2024-01-XX XX:XX

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_org", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField(blank=True, null=True)),
                ("token_expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gmail_token",
                        to="user_org.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "gmail_tokens",
            },
        ),
        migrations.CreateModel(
            name="GmailMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_id", models.CharField(max_length=255, unique=True)),
                ("thread_id", models.CharField(max_length=255)),
                ("subject", models.TextField(blank=True)),
                ("sender", models.EmailField()),
                ("snippet", models.TextField(blank=True)),
                ("is_important", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
                ("labels", models.JSONField(default=list)),
                ("received_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gmail_messages",
                        to="user_org.appuser",
                    ),
                ),
            ],
            options={
                "db_table": "gmail_messages",
                "indexes": [
                    models.Index(
                        fields=["user", "is_important"],
                        name="gmail_messages_user_important_idx",
                    ),
                    models.Index(
                        fields=["user", "is_archived"],
                        name="gmail_messages_user_archived_idx",
                    ),
                    models.Index(
                        fields=["received_at"], name="gmail_messages_received_at_idx"
                    ),
                ],
            },
        ),
    ]
