# Generated by Django 5.2.6 on 2025-09-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gmail_integration",
            "0002_rename_gmail_messages_user_important_idx_gmail_messa_user_id_6ef690_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GmailOAuthState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state", models.CharField(max_length=32, unique=True)),
                ("user_id", models.IntegerField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gmail_oauth_states",
                "indexes": [
                    models.Index(fields=["state"], name="gmail_oauth_state_7699bf_idx"),
                    models.Index(
                        fields=["expires_at"], name="gmail_oauth_expires_84ed0f_idx"
                    ),
                ],
            },
        ),
    ]
