# Generated by Django 5.2.6 on 2025-09-25 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmail_integration", "0003_gmailoauthstate"),
        ("user_org", "0013_appuser_active_org"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gmailoauthstate",
            name="user_id",
        ),
        migrations.AddField(
            model_name="gmailoauthstate",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gmail_oauth_states",
                to="user_org.appuser",
            ),
        ),
    ]
