# Generated by Django 5.1.3 on 2025-02-03 05:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


def create_organizations_for_existing_users(apps, schema_editor):
    AppUser = apps.get_model("releases", "AppUser")
    Organization = apps.get_model("user_org", "Organization")
    Membership = apps.get_model("user_org", "Membership")

    for user in AppUser.objects.all():
        # Create organization for each user
        org = Organization.objects.create(
            name=f"{user.user.email}'s Organization", created_by=user
        )

        # Create membership record with owner role
        Membership.objects.create(user=user, organization=org, role="owner")


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("releases", "0013_alter_appuser_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("read_only", "Read Only"),
                            ("member", "Member"),
                            ("owner", "Owner"),
                        ],
                        default="member",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="releases.appuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="releases.appuser",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="organizations",
                        through="user_org.Membership",
                        to="releases.appuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="membership",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_org.organization"
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user_org.organization",
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            create_organizations_for_existing_users,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
