# Generated by Django 5.1.3 on 2025-02-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_org", "0002_alter_project_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="project",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
