# Generated by Django 5.1.3 on 2025-02-16 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0014_appuser_active_org"),
        ("user_org", "0003_alter_project_options_project_metadata_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.RenameField(
            model_name="project",
            old_name="metadata",
            new_name="inputs",
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="releases.appuser",
            ),
            preserve_default=False,
        ),
    ]
