# Generated by Django 5.1.5 on 2025-02-21 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "user_org",
            "0004_alter_project_options_rename_metadata_project_inputs_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="inputs",
        ),
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
    ]
