# Generated by Django 5.1.3 on 2025-02-24 04:42

import django.db.models.deletion
from django.db import migrations, models


def set_project_users(apps, schema_editor):
    Project = apps.get_model("user_org", "Project")
    Membership = apps.get_model("user_org", "Membership")

    for project in Project.objects.all():
        # Find the owner of the organization through Membership
        owner_membership = Membership.objects.filter(
            organization=project.organization, role="owner"
        ).first()

        if owner_membership:
            project.user = owner_membership.user
            project.save()


def reverse_project_users(apps, schema_editor):
    Project = apps.get_model("user_org", "Project")
    for project in Project.objects.all():
        project.user = None
        project.save()


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0014_appuser_active_org"),
        ("user_org", "0005_remove_project_inputs_remove_project_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="inputs",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="releases.appuser",
            ),
        ),
        migrations.RunPython(set_project_users, reverse_project_users),
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="releases.appuser",
            ),
        ),
    ]
