# Generated by Django 5.1.6 on 2025-03-21 01:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("releases", "0014_appuser_active_org"),
        ("user_org", "0006_project_inputs_project_user"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Project",
            new_name="Workspace",
        ),
    ]
