# Generated by Django 5.1.6 on 2025-04-01 04:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_org", "0007_rename_project_workspace"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnonymousSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["session_key"], name="user_org_an_session_4874b8_idx"
                    )
                ],
            },
        ),
    ]
