# Generated by Django 5.1.6 on 2025-04-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_org", "0008_anonymoussession"),
    ]

    operations = [
        migrations.AddField(
            model_name="anonymoussession",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
