# Generated by Django 5.2.4 on 2025-08-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_org', '0001_squashed_0011_alter_appuser_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='auth_token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
