# Generated by Django 5.2.5 on 2025-08-12 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_org", "0012_alter_appuser_auth_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="active_org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user_org.organization",
            ),
        ),
    ]
